# springdoc의 기본경로 정보와 정렬등을 설정
springdoc:
  swagger-ui:
    path: /swagger.html
    tag-sorter: alpha
    operations-sorter: alpha
    packages-to-scan: com.example.firstproject

  api-doc:
    path: /api-docs

  # 요청과 응답에 대한 기본 mediaType값을 지정
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

#springdoc.swagger-ui.path=/swagger.html
#springdoc.swagger-ui.tags-sorter=alpha
#springdoc.swagger-ui.operations-sorter=alpha
#springdoc.swagger-ui.packages-to-scan=com.example.firstproject
#springdoc.api-docs.path=/api-docs
#
#
#  # 요청과 응답에 대한 기본 mediaType값을 지정
#springdoc.default-consumes-media-type=application/json;charset=UTF-8
#springdoc.default-produces-media-type=application/json;charset=UTF-8